name: Trigger Orchestrator Build

on:
  push:
    paths:
      - 'Migrations/**'  # Se activa si cambian las migraciones
      - 'Toy.Seeder/**'  # Se activa si cambia el código del seeder en C#

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Send Workflow Dispatch to Orchestrator
        run: |
          curl -H "Authorization: token ${{ secrets.ORCHESTRATOR_TRIGGER_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               -X POST \
               -d '{"ref": "no-pci", "inputs": {"network": "nopci"}}' \
               https://api.github.com/repos/fernandourzua/migraciones-test/actions/workflows/deploy.yml/dispatches
